import { Card } from "@/components/ui/card";
import {
  CodeIcon,
  MixerVerticalIcon,
  ReaderIcon,
  RocketIcon,
} from "@radix-ui/react-icons";
import Image from "next/image";
import React from "react";
import api from "@/res/api.png";
import newProject from "@/res/new-project.jpeg";
import newEndpoint from "@/res/new-endpoint.jpeg";
import signUp from "@/res/sign-up-1.jpeg";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
const Page = () => {
  return (
    <div className="mt-16 px-4 sm:px-6 lg:px-8">
      <div className="h-48 md:h-80 mb-32 sm:mb-20 flex flex-col items-center justify-center px-4 ">
        <h1 className="text-4xl md:text-6xl lg:text-7xl font-extrabold my-5 text-center">
          Dummy API
        </h1>
        <p className="max-w-lg md:max-w-4xl opacity-75 text-base md:text-lg lg:text-xl text-justify md:text-center">
          Revolutionize your development workflow with our customizable dummy
          API. Sign up, create projects, define endpoints, configure data, and
          test seamlessly all in one platform. Say goodbye to manual data
          generation and hello to accelerated innovation. Simplify your testing
          process, streamline development, and unleash your creativity with
          ease. Get started today and experience the power of tailored dummy
          data like never before.
        </p>
      </div>

      <div className="text-center mb-10">
        <h4 className="text-xs font-extrabold">FOR DEVELOPER</h4>
        <p className="text-2xl  text-red-400 font-bold my-3">Setup fast.</p>
        <div className="max-w-lg mx-auto break-words">
          <p className="text-wrap text-base  text-center">
            Get your backend done in minutes instead of weeks. <br /> Easily
            build customizable content API and use them with a modern tech stack
            just in few clicks.
          </p>
        </div>
      </div>
      <div className="w-full md:w-7/12 m-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-8 mb-16">
        <Card className=" flex p-3 gap-3 hover:bg-secondary py-4 cursor-pointer">
          <div className="text-center">
            <MixerVerticalIcon className="h-8 w-8 mr-2 mt-2" />
          </div>
          <div className="mt-2">
            <h2 className="text-lg font-semibold mb-3">Customizable</h2>
            <p className="text-sm opacity-75">
              Emphasize the core functionality of your dummy API, which is the
              ability for users to access customizable dummy data. Highlight how
              developers can easily generate test data tailored to their
              specific needs, saving time and effort during the development
              process.
            </p>
          </div>
        </Card>
        <Card className=" flex p-3 gap-3 hover:bg-secondary cursor-pointer py-4">
          <div className="text-center">
            <CodeIcon className="h-8 w-8 mr-2 mt-2" />
          </div>
          <div className="mt-2">
            <h2 className="text-lg font-semibold mb-3">
              Flexible Data Generation
            </h2>
            <p className="text-sm opacity-75">
              Highlight the flexibility of your API in generating various types
              of dummy data. Whether developers need mock user profiles, product
              listings, or transaction records, your API provides the tools to
              create diverse datasets for comprehensive testing scenarios.
            </p>
          </div>
        </Card>
        <Card className=" flex p-3 gap-3 hover:bg-secondary cursor-pointer py-4">
          <div className="text-center">
            <ReaderIcon className="h-8 w-8 mr-2 mt-2" />
          </div>
          <div className="mt-2">
            <h2 className="text-lg font-semibold mb-3">
              Realistic Simulation Capabilities
            </h2>
            <p className="text-sm opacity-75">
              Highlight the realism of the dummy data generated by your API.
              Explain how the data closely resembles real-world scenarios,
              enabling developers to simulate authentic user interactions, edge
              cases, and system behaviors during testing.
            </p>
          </div>
        </Card>
        <Card className=" flex p-3 gap-3 hover:bg-secondary cursor-pointer pb-4">
          <div className="text-center">
            <RocketIcon className="h-8 w-8 mr-2 mt-2" />
          </div>
          <div className="mt-2">
            <h2 className="text-lg font-semibold mb-3">Cost-Effective</h2>
            <p className="text-sm opacity-75">
              Emphasize the cost-effectiveness of using your dummy API for
              testing and development purposes. Unlike accessing real data
              sources or setting up complex testing environments, your API
              provides a budget-friendly solution that helps reduce overhead
              costs.
            </p>
          </div>
        </Card>
      </div>
      <div className="max-w-screen-xl mx-auto">
        <div>
          <h4 className="text-xs font-extrabold text-center mt-5">
            STEP-BY-STEP GUIDE
          </h4>
          <p className="text-2xl text-red-400 font-bold my-3 text-center">
            How does it work?
          </p>
          <div className="max-w-lg mx-auto break-words mb-16">
            <p className="text-wrap text-base text-center">
              Make a flexible data structure in 2 minutes. Use our powerful
              features to customize your API.
            </p>
          </div>
          <div className="p-4 flex flex-col sm:flex-row justify-around  gap-8 mb-8">
            <div className="sm:w-1/2">
              <p className="mb-8 font-bold underline">Step 1</p>
              <h2 className="mb-8 w-[400px] text-2xl  font-semibold">
                Sign Up.
              </h2>
              <p className="text-base opacity-75">
                Begin your journey with the dummy API by signing up for an
                account. This initial step grants you access to a suite of tools
                designed to simplify the process of generating custom dummy
                data. Signing up is quick and straightforward, requiring only
                basic information to get started. Registration grants you access
                to a powerful platform for generating customizable dummy data.
                Signing up is quick and easy, requiring only basic information
                to get started.
              </p>
            </div>
            <div className="sm:w-1/2">
              <Card className="p-2">
                <Image src={signUp} alt="loading" width={1000} height={500} />
              </Card>
            </div>
          </div>
          <div className="p-4 flex flex-col-reverse sm:flex-row justify-around  gap-8 mb-8">
            <div className="sm:w-1/2">
              <Card className="py-4">
                <Image
                  width={1000}
                  height={500}
                  src={newProject}
                  alt="loading"
                  className="mx-auto h-5/6 w-5/6"
                />
              </Card>
            </div>
            <div className="sm:w-1/2">
              <p className="mb-8 font-bold underline">Step 2</p>
              <h2 className="mb-8 w-[400px] text-2xl font-semibold">
                Create a Project
              </h2>
              <p className="text-base opacity-75">
                Once logged in, create a new project to encapsulate your dummy
                data configurations. Projects serve as organizational
                containers, allowing you to manage and customize multiple sets
                of dummy data independently. Think of projects as virtual
                workspaces where you can define and refine your data generation
                settings.
              </p>
            </div>
          </div>
          <div className="p-4 flex flex-col sm:flex-row justify-around  gap-8 mb-8">
            <div className="sm:w-1/2">
              <p className="mb-8 font-bold underline">Step 3</p>
              <h2 className="mb-8 w-[400px] text-2xl font-semibold">
                Define Endpoints and Fields
              </h2>
              <p className="text-base opacity-75">
                Within your project, define endpoints to represent the various
                types of data you want to simulate, such as users, products, or
                orders. Each endpoint serves as a distinct data source, and you
                can customize them by adding specific fields to mimic real-world
                attributes. For instance, a user endpoint might include fields
                for names, email addresses, and ages, while a product endpoint
                might include fields for names, descriptions, and prices.
              </p>
            </div>
            <div className="sm:w-1/2">
              <Card className="py-2">
                <Image
                  width={1000}
                  height={500}
                  src={newEndpoint}
                  alt="loading"
                  className="mx-auto h-5/6 w-5/6"
                />
              </Card>
            </div>
          </div>
          <div className="p-4 flex flex-col-reverse sm:flex-row justify-around  gap-8 mb-8">
            <div className="sm:w-1/2">
              <Card className="py-4">
                <Image
                  width={1000}
                  height={500}
                  src={api}
                  alt="loading"
                  className="mx-auto h-5/6 w-5/6"
                />
              </Card>
            </div>
            <div className="sm:w-1/2">
              <p className="mb-8 font-bold underline">Step 4</p>
              <h2 className="mb-8 w-[400px] text-2xl font-semibold">
                Test the API
              </h2>
              <p className="text-base opacity-75">
                After setting up your project and configuring your data
                generation settings, it is time to test the API to ensure
                everything is working as expected. Utilize the provided testing
                tools or make API requests using your preferred method, such as
                command-line tools like cURL or dedicated API testing software.
                Verify that the generated dummy data aligns with your
                expectations and meets the requirements of your testing or
                development scenarios. By thoroughly testing the API, you can
                identify any potential issues or discrepancies early on and make
                any necessary adjustments to your configurations.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="p-2 max-sm:m-5 mx-auto max-w-screen-lg">
        <h1 className="text-center font-extrabold text-2xl">F&Q</h1>
        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="item-1">
            <AccordionTrigger className="text-start">
              Why do we need to login?
            </AccordionTrigger>
            <AccordionContent>
              We require login to differentiate users&apos; APIs effectively. By
              logging in, users gain access to personalized features and project
              management tools tailored to their specific needs. This ensures a
              seamless experience while enabling us to provide customized
              support and security measures for each user&apos;s API configurations.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger className="text-start">
              Can it be used for production as-is?
            </AccordionTrigger>
            <AccordionContent>
              While our dummy API is primarily designed for testing and
              development purposes, it may not be suitable for production use
              without further consideration. The data generated by the API is
              synthetic and intended for simulation rather than real-world
              scenarios. Additionally, performance, security, and scalability
              factors should be carefully evaluated before deploying any
              application to production. We recommend thorough testing and
              potential adjustments to ensure compatibility with production
              environments.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger className="text-start">
              Is the dummy API suitable for generating large volumes of data?
            </AccordionTrigger>
            <AccordionContent>
              Yes, the dummy API can handle generating large volumes of data
              efficiently. However, users should consider their system&apos;s
              resources and performance requirements when configuring data
              generation settings to ensure optimal performance.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger className="text-start">
              Can I customize the format and structure of the dummy data
              generated by the API?
            </AccordionTrigger>
            <AccordionContent>
              Absolutely! Our API provides flexibility in customizing the format
              and structure of the generated data. Users can define endpoints,
              add fields, and configure data generation settings according to
              their specific requirements.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-5">
            <AccordionTrigger className="text-start">
              Are there any limitations on the number of projects or endpoints I
              can create?
            </AccordionTrigger>
            <AccordionContent>
              There are no predefined limitations on the number of projects or
              endpoints you can create. Users can create and manage multiple
              projects and endpoints based on their needs. However, we recommend
              organizing your projects and endpoints efficiently to maintain
              clarity and manageability.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-6">
            <AccordionTrigger className="text-start">
              Is the dummy data generated by the API realistic and suitable for
              comprehensive testing scenarios?
            </AccordionTrigger>
            <AccordionContent>
              While the dummy data is synthetic and intended for testing and
              development purposes, we strive to make it as realistic as
              possible. Users can customize data generation settings to simulate
              diverse real-world scenarios, including different user
              demographics, dynamic content updates, and complex data
              relationships, making it suitable for a wide range of testing
              scenarios.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
};

export default Page;
